# Generated by Django 5.0.3 on 2024-03-12 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='dst',
            field=models.CharField(choices=[('E', 'Europe'), ('A', 'Us Canada'), ('S', 'South America'), ('O', 'Australia'), ('Z', 'New Zealand'), ('U', 'Unknown')], default='U', max_length=2, null=True),
        ),
    ]
