# Generated by Django 5.0.3 on 2024-03-16 10:08
from datetime import timedelta

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='arrival_datetime',
        ),
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.DurationField(default=timedelta(hours=1)),
            preserve_default=False,
        ),
    ]
