version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: web/Dockerfile.prod
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
    expose:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.db
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - static_volume:/home/app/web/static

  redis:
    image: redis:alpine
    ports:
      - 6379:6379

volumes:
  postgres_data:
  static_volume:
