# Generated by Django 5.0.3 on 2024-03-17 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_passenger_created_at_passenger_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='options',
        ),
        migrations.AlterField(
            model_name='ticketoption',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='bookings.ticket'),
        ),
    ]
