# Generated by Django 5.0.3 on 2024-03-17 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_ticket_options_alter_ticketoption_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='seat_type',
            field=models.CharField(choices=[('Economy', 'E'), ('Business', 'B')], default='E', max_length=32),
            preserve_default=False,
        ),
    ]
