# Generated by Django 5.0.3 on 2024-03-17 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_ticket_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='bookings.booking'),
        ),
    ]
