# Generated by Django 5.0.3 on 2024-03-22 11:25

import secrets
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_booking_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AddField(
            model_name='ticket',
            name='number',
            field=models.CharField(default=secrets.token_hex(10), max_length=64),
            preserve_default=False,
        ),
    ]
